### ISSUE TITLE
Bug in BYO Planner code - documentation

### ISSUE THREAD

**Issue by gballardin** [awslabs/amazon-accessible-rl-sdk#22]
Applying my own data to the [BYO Planner](https://awslabs.github.io/amazon-accessible-rl-sdk/auto-notebooks/planner_byo_example.html) code it fails for the Behavioural Clone Planner part, specifically in this line of code:

`immediate_cost = df_sar[tokenizer.df_tokenized.rewards[:-1]].values`

The reason why it fails is because it assumes that `tokenizer.df_tokenized.rewards` is a list with more than one element and it can therefore apply `[:-1]`. In my case though:
```
len(tokenizer.df_tokenized.rewards)
1
```
which leads to:
```
tokenizer.df_tokenized.rewards[:-1]
[]
```
and finally:
```
df_sar[tokenizer.df_tokenized.rewards[:-1]].values
array([], shape=(1, 0), dtype=float64)
```
Should this be instead something like:

`immediate_cost = immediate_cost = df_sar[tokenizer.df_tokenized.rewards[:-1 if len(tokenizer.df_tokenized.rewards)>1 else 0]].values`

**Comment by verdimrc** [comment]
You're right, and it might be even simplified to `.rewards[0:1]`.

**Comment by verdimrc** [comment]
Btw, the reason why the BYO example assumes 2 columns is because of the additional `value` column created by `add_value()`. Any chance you skip this `add_value()` part?

The simulator is designed with `value` presented. @yapweiyih: any idea what might happen when simulator doesn't see `value`?

**Comment by gballardin** [comment]
I did I ran `.add_value()` originally, but I think what happened is that the Jupyter kernel died and I must have resumed my code without re-running `.add_value()` from the top and that is where I tripped. You're right, when I now re-run it from scratch with `.add_value()` the problem is no longer there.

Thank you for looking into this.
